services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  springboot-app:
    build:
      context: ./
    container_name: springboot_app
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db:27017/test
      SPRING_REDIS_HOST: redis_cache
      SPRING_REDIS_PORT: 6379

  frontend:
    build:
      context: ./react-frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - springboot-app


volumes:
  postgres_data:
  mongo_data:
